services:

  holiday-info-service:
    image: holiday-info/holiday-info-service:${PROJECT_VERSION}
    env_file: .env
    networks:
      - holiday-info-network
    ports:
      - '8080:8080'
    restart: on-failure:5
    logging: &logging
      driver: "json-file"
      options:
        max-size: ${LOG_MAX_SIZE}
        max-file: ${LOG_MAX_FILE}

#  nginx:
#    image: nginx:${NGINX_VERSION}
#    env_file: .env
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - holiday-info-service
#    ports:
#      - '80:80'
#    networks:
#      - holiday-info-network
#    restart: on-failure:5
#    logging:
#      <<: *logging
# TODO: add healthcheck for nginx
# TODO: enable nginx, add ssl

networks:
  holiday-info-network:
    driver: bridge
